# array initializing and general properties

In [1]:
import numpy as np


In [2]:
arr = np.array([1,12,34,5])

In [3]:
print(arr)

[ 1 12 34  5]


In [4]:
#get dimension
arr.ndim

1

In [19]:
arr= np.array([[1,2],[3,4],[5,6]], dtype='int32')
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
arr.ndim


2

In [7]:
#get shape 


In [8]:
arr.shape


(3, 2)

In [9]:
#get type

In [10]:
arr.dtype


dtype('int32')

In [21]:
arr.dtype


dtype('int32')

In [20]:
arr.itemsize

4

In [22]:
arr.dtype = "int8"

In [23]:
arr.dtype

dtype('int8')

In [24]:
arr.itemsize

1

In [25]:
arr.size


24

In [26]:
a= np.array([1,2,3])

In [27]:
print(a)

[1 2 3]


In [28]:
a.size


3

In [29]:
a.size


3

In [30]:
a.dtype


dtype('int32')

In [31]:
a.ndim

1

In [32]:
a.shape

(3,)

In [33]:
a.itemsize


4

In [34]:
a.size * a.itemsize


12

In [35]:
a.nbytes


12